### PR TITLE
Restructure R utility functions and add wrappers

### PR DESCRIPTION
**Pull request by maltelueken**
Closes Nlesc-team/Sushi#252

Restructures the R utility functions (moves all function declarations into the same file).

Removes old C++ and R likelihood functions to avoid confusion with pure C++ functions.

Adds wrappers for the utility functions. They work as the wrappers for the geometry functions (see #7).

### CODE REVIEW

**Comment by n400peanuts** [comment]
@maltelueken I can't approve this PR as there are issues with codecov/patch that needs to be addressed. New contributions should have a coverage at least equal to target (i.e., 80.71%) -- if you do not wish to amend this issue you could consider commenting out the patch. Up to you.

**Comment by maltelueken** [comment]
Yes, that is because I didn't write extra tests for the wrappers yet (because the functions they call are already tested). I will add them.

**Comment by maltelueken** [comment]
The checks pass now, so this can be merged!

**Review by n400peanuts — APPROVED** [review]
lgtm

**Pull request merged**
